import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>makeitez.ru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Домен продается
        </h1>

        <p className={styles.description}>
         <a href="mailto:vodolazskikh@yandex.ru" className={styles.link}>емейл</a>
         <a href="https://t.me/vodolazskikh" className={styles.link}>телеграм</a>
        </p>
      </main>
    </div>
  )
}

export default Home
